export const MQTT_EVENTS = {
    // PROJECTS
    GET_ALL_PROJECTS: '[IOT-BRD] GET_ALL_PROJECTS',
    GET_PROJECT_BY_ID: '[IOT-BRD] GET_PROJECT_BY_ID',
    CREATED_ONE_PROJECT: '[IOT-BRD] CREATED_ONE_PROJECT',
    DELETED_ONE_PROJECT: '[IOT-BRD] DELETED_ONE_PROJECT',
    UPDATED_ONE_PROJECT: '[IOT-BRD] UPDATED_ONE_PROJECT',
    // SENSORS
    GET_ALL_SENSORS: '[IOT-BRD] GET_ALL_SENSORS',
    GET_SENSOR_BY_ID: '[IOT-BRD] GET_SENSOR_BY_ID',
    GET_SENSOR_BY_NAME: '[IOT-BRD] GET_SENSOR_BY_NAME',
    CREATED_ONE_SENSOR: '[IOT-BRD] CREATED_ONE_SENSOR',
    DELETED_ONE_SENSOR: '[IOT-BRD] DELETED_ONE_SENSOR',
    UPDATED_ONE_SENSOR: '[IOT-BRD] UPDATED_ONE_SENSOR',
}