name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-admin-api-microservice:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image for the admin-api service
      run: docker build . --file Dockerfile --tag iot-board-admin-api:$(date +%s) --build-arg APP_NAME=iot-board-admin-api
  
  build-sensors-api-microservice:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image for the sensors-api service
      run: docker build . --file Dockerfile --tag iot-board-sensors-api:$(date +%s) --build-arg APP_NAME=iot-board-sensors-api
